<!DOCTYPE html>
<html lang="ja">
    <div>
        <?php
            for($i=1;$i<=50;$i++){
                print($i."");
            }
        ?>
        <?php
            for($i=51;$i<=100;$i++){
                print($i."");
            }
        ?>
        <?php
            for($i=101;$i<=140;$i++){
                print($i."");
            }
        ?>
        <?php
            for($i=141;$i<=180;$i++){
                print($i."");
            }
        ?>
        <?php
            for($i=181;$i<=220;$i++){
                print($i."");
            }
        ?>
        <?php
            for($i=221;$i<=260;$i++){
                print($i."");
            }
        ?>
        <?php
            for($i=261;$i<=300;$i++){
                print($i."");
            }
        ?>
        <?php
            for($i=301;$i<=340;$i++){
                print($i."");
            }
        ?>
        <?php
            for($i=341;$i<=365;$i++){
                print($i."");
            }
        ?>
    </div>